@baseUrl  = http://localhost:7653/v1
@countryId = 13

###
GET {{baseUrl}} HTTP/1.1

###
GET {{baseUrl}}/countries HTTP/1.1

###
GET {{baseUrl}}/countries/{{countryId}} HTTP/1.1

###
GET {{baseUrl}}/countries/{{countryId}}/provinces HTTP/1.1