// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Country struct {
	ID          int32       `json:"id"`
	IsoCode3    string      `json:"iso_code3"`
	CountryName string      `json:"country_name"`
	DialingCode pgtype.Text `json:"dialing_code"`
}

type Province struct {
	ID           int32       `json:"id"`
	CountryID    int32       `json:"country_id"`
	ProvinceName string      `json:"province_name"`
	Code         pgtype.Text `json:"code"`
}
