// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package zvizivisodb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Country struct {
	ID          int32       `json:"id"`
	IsoCode3    string      `json:"iso_code3"`
	Name        string      `json:"name"`
	DialingCode pgtype.Text `json:"dialing_code"`
}

type Province struct {
	ID        int32       `json:"id"`
	CountryID int32       `json:"country_id"`
	Name      string      `json:"name"`
	Code      pgtype.Text `json:"code"`
}
