// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package zvizivisodb

import (
	"context"
)

type Querier interface {
	GetCountry(ctx context.Context, id int32) (Country, error)
	ListCountries(ctx context.Context, arg ListCountriesParams) ([]Country, error)
}

var _ Querier = (*Queries)(nil)
