// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	GetCountry(ctx context.Context, id int32) (Country, error)
	GetProvincesByCountryId(ctx context.Context, countryID int32) ([]Province, error)
	GetProvincesById(ctx context.Context, id int32) (Province, error)
	GetUserByEmailOrUsername(ctx context.Context, arg GetUserByEmailOrUsernameParams) ([]User, error)
	ListCountries(ctx context.Context) ([]Country, error)
}

var _ Querier = (*Queries)(nil)
